// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/shohinsan/GopherQL/graph"
	mock "github.com/stretchr/testify/mock"
)

// TweetResolver is an autogenerated mock type for the TweetResolver type
type TweetResolver struct {
	mock.Mock
}

// Replies provides a mock function with given fields: ctx, obj
func (_m *TweetResolver) Replies(ctx context.Context, obj *graph.Tweet) ([]*graph.Tweet, error) {
	ret := _m.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Replies")
	}

	var r0 []*graph.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *graph.Tweet) ([]*graph.Tweet, error)); ok {
		return rf(ctx, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *graph.Tweet) []*graph.Tweet); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *graph.Tweet) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User provides a mock function with given fields: ctx, obj
func (_m *TweetResolver) User(ctx context.Context, obj *graph.Tweet) (*graph.User, error) {
	ret := _m.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *graph.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *graph.Tweet) (*graph.User, error)); ok {
		return rf(ctx, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *graph.Tweet) *graph.User); ok {
		r0 = rf(ctx, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *graph.Tweet) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTweetResolver creates a new instance of TweetResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTweetResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *TweetResolver {
	mock := &TweetResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
